language: python
python:
- "3.4"
services: memcached
before_install:
    - sudo apt-get install -y libmemcached-dev
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: coverage run --include="snippets/*" --omit="snippets/migrations/*" manage.py test
after_success:
    coveralls
